source "https://rubygems.org"

gem "jekyll", "~> 3.0"
gem "jekyll-sitemap"
gem "jekyll-gist"

group :jekyll_plugins do
  gem 'octopress', '~> 3.0.11'
  gem 'octopress-codeblock', '~> 1.0'
  gem 'octopress-image-tag', '~> 1.1'
end
