# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Philippe Bourgau's Blog
email: philippe.bourgau@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A programming blog. Particularly about agile development, real world walkthrough, tutorials, side project entrepreneurship and open source software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://philippe.bourgau.net" # the base hostname & protocol for your site
twitter_username: pbourgau
github_username:  philou
permalink: /:title/

# Build settings
markdown: kramdown

# Excluded directories
exclude: [vendor]
